# Generated by Django 2.2.26 on 2022-02-11 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20220210_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='pictures',
            new_name='picture',
        ),
    ]
